### ISSUE TITLE
The problem of org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer 

### ISSUE THREAD

**Issue by linqingying123** [eclipse-lsp4j/lsp4j#811] opened 2024-02-18 14:21 UTC
About the fireError method of the org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer class frequently reports an error Missing header Content-Length in input "
"
Java.lang.IllegalStateException: Missing header Content-Length in input "
"but it has no effect in use. Why not show this error?"

**Comment by jonahgraham** [comment] 2024-02-18 14:24
Can you provide additional information about how to reproduce this please? Or a sample trace that produces the issue you are experiencing.

**Comment by linqingying123** [comment] 2024-02-18 14:29
Sorry, the machine translation may not translate what I want to express, I mean in line 72 of org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer "if (headers.contentLength < 0) {.
This.fireError (new IllegalStateException ("Missing header Content-Length in input\"+ debugBuilder +"\ ")).
} else {.
Boolean result = this.handleMessage (this.input, headers).
If (! result) {.
This.keepRunning = false.
}.

NewLine = false.
The this.fireError method called in "}" prints an error log (because the server did not send a complete message), and the error is displayed in intellij, but I do not want to show this error

**Comment by jonahgraham** [comment] 2024-02-18 14:39
That error happens when the server sends an incomplete message, as you have concluded. But I don't know what change you want LSP4J to make. The error is logged, but if it is displayed in a way you don't like in intellij, should that be filled to intellij?

If I recall correctly you can extend and wire in your own subclass of StreamMessageProducer and in that subclass override fireError to have different behaviour.

**Comment by linqingying123** [comment] 2024-02-18 14:42
Thank you for reminding me that the project is too bloated and has forgotten how to write it before. I'm sorry I wasted your time.

**Comment by jonahgraham** [comment] 2024-02-18 15:01
I assume the machine translation wrote that last message as I don't think it came across as you may have intended.

Closing for now as it seems there is nothing else for the LSP4J project to do here.

**Closed** 2024-02-18 15:01 UTC
Labels: more info needed
